name: CI

on:
  push:
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true    
      - name: Style check
        run: cargo fmt --all -- --check
      - name: Clippy check
        run: cargo clippy --all-targets --all-features
      - name: Install macros expand
        run: cargo install cargo-expand
      - name: Expand emulation
        run: cargo expand emulation --all-features
      - name: Expand emulation chrome
        run: cargo expand emulation::device::chrome --all-features
      - name: Expand emulation firefox
        run: cargo expand emulation::device::firefox --all-features
      - name: Expand emulation safari
        run: cargo expand emulation::device::safari --all-features
      - name: Expand emulation okhttp
        run: cargo expand emulation::device::okhttp --all-features

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build docs
        run: cargo doc --document-private-items --all-features

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Tests
        run: | 
          set -euxo pipefail
          cargo nextest run --workspace --all-features

  linux:
    name: Linux
    needs: [style, tests, docs]
    runs-on: ubuntu-latest
    environment: Linux
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          generate_release_notes: true
